### ISSUE TITLE
Can `requirements.txt` dependencies be streamlined/relaxed?

### ISSUE THREAD

**Issue by cooperrc** [rland93/pendsim#11]
@rland93, I'm reviewing [PendSim software](https://github.com/openjournals/jose-reviews/issues/168) with JOSE and ran into installation issue _might be an issue on my end or NumPy version that's pinned, 

following the [docs installation](https://rland93.github.io/pendsim/install.html)

```bash
git clone https://github.com/rland93/pendulum.git
cd pendulum
pip install -r requirements.txt
```

Most of the `requirements` seem to install, but then NumPy 1.21.1 throws a big error. 

```
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
```

A question: Are all of the packages listed in `requirements.txt` required? or is this an autogenerated requirements package?

Maybe some of the pinned versions could be removed from `requirements.txt`?

**Comment by rland93** [comment]
Yes, `requirements.txt` was just the output of `pip freeze`.

Resolved!

One more thing to note: I renamed `master` to `main`, which might cause issues if you pull from your local. If that's the case you can delete and clone again.

Thanks for the review!
